version: '3'
services:
  node:
    image: node:8.6.0
    restart: on-failure
    environment:
      - POSTGRES_USER=user
      - POSTGRES_HOST=postgres
      - EXPRESS_PORT=3000
      - POSTGRES_PORT=5432
    env_file: ${NODE_ENV:-development}.env
    ports:
      - "3000:3000"
    command: bash -c "cd /var/lib/node/server/ && npm install && NODE_ENV=${NODE_ENV:-development} npm run start"
    volumes:
      - ../server/:/var/lib/node/server/
      - node_modules:/var/lib/node/server/node_modules
    networks:
      - kotori
    logging:
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "100"
  postgres:
    build: ../echoprint/postgres_echoprint/
    restart: always
    environment:
      - POSTGRES_USER=user
      - PGDATA=${NODE_ENV:-development}
    env_file: ${NODE_ENV:-development}.env
    expose:
      - "5432"
    volumes:
      - ./postgresql/etc/:/etc/postgresql
      - pg_data:/var/lib/postgresql/data
      - ./logs/postgresql/:/var/log/postgresql
      - ./../server/db/postgres.sql:/docker-entrypoint-initdb.d/ycreate-postgres.sql
      - ./../server/db/create_testdb.sql:/docker${NODE_ENV--}entrypoint-initdb.d/zcreate_testdb.sql
    networks:
      - kotori
volumes:
  node_modules:
  pg_data:
networks:
  kotori:
    driver: bridge
