version: '3'
services:
  node:
    image: node:8.6.0
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=E.pL0_UJoia,:IB4
      - POSTGRES_USER=user
      - POSTGRES_HOST=postgres
      - EXPRESS_PORT=3000
    ports:
      - "3000:3000"
    command: bash -c "cd /var/lib/node/server/ && npm install && npm run start"
    volumes:
      - ../server/:/var/lib/node/server/
      - node_modules:/var/lib/node/server/node_modules
    logging:
      driver: json-file
      options:
        max-size: "1024k"
        max-file: "100"
  postgres:
    build: ../echoprint/postgres_echoprint/
    restart: always
    environment:
      - POSTGRES_PASSWORD=E.pL0_UJoia,:IB4
      - POSTGRES_USER=user
      - POSTGRES_DB=kotori_test
    expose:
      - "5432"
    volumes:
      - ./postgresql/etc/:/etc/postgresql
      - pg_data:/var/lib/postgresql/data
      - ./logs/postgresql/:/var/log/postgresql
      - ./../server/db/:/tmp/postgres/
      - ./../server/db/create_testdb.sql:/docker-entrypoint-initdb.d/zcreate_testdb.sql
volumes:
  node_modules:
  pg_data: